# Generated by Django 3.0.8 on 2020-07-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_welcome_updated2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welcome',
            name='updated2',
        ),
    ]
