# Generated by Django 3.0.8 on 2020-08-02 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=255)),
                ('animal_age', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name_plural': 'Animales',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='AnimalColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Color de animal',
                'verbose_name_plural': 'Color de animales',
            },
        ),
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de animal',
                'verbose_name_plural': 'Tipos de animales',
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=255)),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.AnimalType')),
            ],
            options={
                'verbose_name': 'Raza de animal',
                'verbose_name_plural': 'Razas',
            },
        ),
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_description', models.TextField(verbose_name='Descripción de la imagen')),
                ('image_url', models.ImageField(default='media/None/no-img.jpg', upload_to='animal/', verbose_name='Url par imagen')),
                ('main', models.BooleanField(default=False, verbose_name='Principal')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('image_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Animal', verbose_name='Imagen de animal')),
            ],
            options={
                'verbose_name_plural': 'Imagenes por animal',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='animal.Breed'),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='animal.AnimalColor'),
        ),
    ]
