# Generated by Django 3.0.8 on 2020-08-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalimage',
            name='main',
            field=models.BooleanField(default=False, unique=True, verbose_name='Principal'),
        ),
    ]
