# Generated by Django 3.0.8 on 2020-07-12 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_auto_20200711_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['created'], 'verbose_name_plural': 'Animales'},
        ),
        migrations.AlterModelOptions(
            name='animalcolor',
            options={'verbose_name': 'Color de animal', 'verbose_name_plural': 'Color de animales'},
        ),
        migrations.AlterModelOptions(
            name='animaltype',
            options={'verbose_name': 'Tipo de animal', 'verbose_name_plural': 'Tipos de animales'},
        ),
        migrations.AlterModelOptions(
            name='breed',
            options={'verbose_name': 'Raza de animal', 'verbose_name_plural': 'Razas'},
        ),
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_description', models.TextField()),
                ('image_url', models.ImageField(default='media/None/no-img.jpg', upload_to='animal/')),
                ('image_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Animal')),
            ],
        ),
    ]
