# Generated by Django 3.0.8 on 2020-07-31 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_auto_20200712_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='animal_image',
        ),
    ]
